import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../students/models/student.dart';
import '../models/report_data.dart';

class PdfGenerator {
  static Future<Uint8List> generatePdf(ReportData report) async {
    final pdf = pw.Document();

    final primaryColor = PdfColor.fromHex('#2563EB'); // Clean M3 primary blue
    final darkColor = PdfColor.fromHex('#1E293B');
    final greyColor = PdfColor.fromHex('#64748B');
    final lightBg = PdfColor.fromHex('#F8FAFC');
    final borderColor = PdfColor.fromHex('#E2E8F0');

    // Page 1: Cover & Executive Summary
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        footer: (context) => _buildFooter(context, report),
        build: (context) => [
          // Header / Cover Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    report.ownerProfile.libraryName.isNotEmpty
                        ? report.ownerProfile.libraryName
                        : 'Library Management System',
                    style: pw.TextStyle(
                      fontSize: 20,
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    report.ownerProfile.branchName.isNotEmpty
                        ? report.ownerProfile.branchName
                        : 'Main Branch',
                    style: pw.TextStyle(fontSize: 11, color: greyColor),
                  ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                    decoration: pw.BoxDecoration(
                      color: lightBg,
                      borderRadius: pw.BorderRadius.circular(6),
                      border: pw.Border.all(color: borderColor),
                    ),
                    child: pw.Text(
                      report.reportType.toUpperCase(),
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: primaryColor,
                      ),
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'Generated: ${report.generatedDate}',
                    style: pw.TextStyle(fontSize: 9, color: greyColor),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Divider(color: borderColor, thickness: 1),
          pw.SizedBox(height: 16),

          // Cover Title Banner
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: lightBg,
              borderRadius: pw.BorderRadius.circular(8),
              border: pw.Border.all(color: borderColor),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'PERIOD REPORT',
                  style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: greyColor),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  report.selectedPeriod,
                  style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: darkColor),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Generated By: ${report.ownerProfile.name}',
                  style: pw.TextStyle(fontSize: 11, color: darkColor),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Section 1: Summary Grid
          _buildSectionHeader('1. Executive Summary'),
          pw.SizedBox(height: 10),
          pw.GridView(
            crossAxisCount: 4,
            childAspectRatio: 2.2,
            crossAxisSpacing: 8,
            mainAxisSpacing: 8,
            children: [
              _buildMetricCard('Total Students', '${report.totalStudents}', darkColor, lightBg, borderColor),
              _buildMetricCard('New Admissions', '${report.newAdmissions}', darkColor, lightBg, borderColor),
              _buildMetricCard('Renewals', '${report.renewals}', darkColor, lightBg, borderColor),
              _buildMetricCard('Expired', '${report.expiredMemberships}', darkColor, lightBg, borderColor),
              _buildMetricCard('Occupied Seats', '${report.occupiedSeats}', darkColor, lightBg, borderColor),
              _buildMetricCard('Available Seats', '${report.availableSeats}', darkColor, lightBg, borderColor),
              _buildMetricCard('Total Collection', 'Rs. ${report.totalCollection.toStringAsFixed(0)}', darkColor, lightBg, borderColor),
              _buildMetricCard('Pending Fees', 'Rs. ${report.pendingFees.toStringAsFixed(0)}', darkColor, lightBg, borderColor),
            ],
          ),
          pw.SizedBox(height: 20),

          // Section 2: Payment Summary
          _buildSectionHeader('2. Payment Summary'),
          pw.SizedBox(height: 10),
          pw.TableHelper.fromTextArray(
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 10),
            headerDecoration: pw.BoxDecoration(color: primaryColor),
            rowDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: borderColor))),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellPadding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
            headers: ['Payment Mode', 'Collection Amount'],
            data: [
              ['Cash', 'Rs. ${report.cashPayment.toStringAsFixed(2)}'],
              ['UPI / Online', 'Rs. ${report.upiPayment.toStringAsFixed(2)}'],
              ['Bank Transfer', 'Rs. ${report.bankPayment.toStringAsFixed(2)}'],
              ['Total Revenue', 'Rs. ${report.totalRevenue.toStringAsFixed(2)}'],
            ],
          ),
          pw.SizedBox(height: 24),

          // Section 3: Student List
          _buildSectionHeader('3. Student List'),
          pw.SizedBox(height: 10),
          _buildStudentTable(report.studentList, primaryColor, borderColor),
          pw.SizedBox(height: 24),

          // Section 4: Payment History
          _buildSectionHeader('4. Payment History'),
          pw.SizedBox(height: 10),
          _buildPaymentTable(report.paymentHistory, primaryColor, borderColor),
          pw.SizedBox(height: 24),

          // End of report signature block
          pw.Container(
            alignment: pw.Alignment.center,
            padding: const pw.EdgeInsets.all(12),
            child: pw.Text(
              '*** End of Report - Generated by Library Management System ***',
              style: pw.TextStyle(fontSize: 9, color: greyColor, fontStyle: pw.FontStyle.italic),
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildSectionHeader(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('#1E293B')),
    );
  }

  static pw.Widget _buildMetricCard(String title, String value, PdfColor textCol, PdfColor bgCol, PdfColor borderCol) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: bgCol,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: borderCol),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          pw.Text(title, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          pw.SizedBox(height: 2),
          pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: textCol)),
        ],
      ),
    );
  }

  static pw.Widget _buildStudentTable(List studentList, PdfColor headerBg, PdfColor borderCol) {
    if (studentList.isEmpty) {
      return pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 8),
        child: pw.Text('No student records for this period.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      );
    }
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 9),
      headerDecoration: pw.BoxDecoration(color: headerBg),
      rowDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: borderCol))),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      headers: ['Name', 'Seat', 'Plan', 'Joining Date', 'Expiry Date', 'Status'],
      data: studentList.map((s) => [
        s.name,
        s.seat.isNotEmpty ? s.seat : 'N/A',
        s.membership == MembershipType.fullTime ? 'Full Time' : 'Half Time',
        s.joined,
        s.expiry,
        s.payment.toString().split('.').last.toUpperCase(),
      ]).toList(),
    );
  }

  static pw.Widget _buildPaymentTable(List history, PdfColor headerBg, PdfColor borderCol) {
    if (history.isEmpty) {
      return pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 8),
        child: pw.Text('No payment records recorded for this period.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
      );
    }
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 9),
      headerDecoration: pw.BoxDecoration(color: headerBg),
      rowDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: borderCol))),
      cellStyle: const pw.TextStyle(fontSize: 9),
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      headers: ['Receipt No', 'Student Name', 'Date', 'Amount', 'Mode'],
      data: history.map((p) => [
        p.receiptNo,
        p.studentName,
        p.paymentDate,
        'Rs. ${p.amount.toStringAsFixed(2)}',
        p.mode,
      ]).toList(),
    );
  }

  static pw.Widget _buildFooter(pw.Context context, ReportData report) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 10),
      padding: const pw.EdgeInsets.only(top: 6),
      decoration: const pw.BoxDecoration(border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300))),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            report.ownerProfile.libraryName.isNotEmpty ? report.ownerProfile.libraryName : 'Library Management System',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }
}
