// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForLibraryManagment6bf3f',
    appId: '1:1049749225213:web:6bf3f10293847561029384',
    messagingSenderId: '1049749225213',
    projectId: 'library-managment-6bf3f',
    authDomain: 'library-managment-6bf3f.firebaseapp.com',
    storageBucket: 'library-managment-6bf3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvnI0naFtguKmzcvMqAB3ezZk-862YzT0',
    appId: '1:1049749225213:android:5db15f4c81fd4171804894',
    messagingSenderId: '1049749225213',
    projectId: 'library-managment-6bf3f',
    storageBucket: 'library-managment-6bf3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForLibraryManagment6bf3f',
    appId: '1:1049749225213:ios:6bf3f10293847561029384',
    messagingSenderId: '1049749225213',
    projectId: 'library-managment-6bf3f',
    storageBucket: 'library-managment-6bf3f.appspot.com',
    iosBundleId: 'com.shelf.shelfFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForLibraryManagment6bf3f',
    appId: '1:1049749225213:ios:6bf3f10293847561029384',
    messagingSenderId: '1049749225213',
    projectId: 'library-managment-6bf3f',
    storageBucket: 'library-managment-6bf3f.appspot.com',
    iosBundleId: 'com.shelf.shelfFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForLibraryManagment6bf3f',
    appId: '1:1049749225213:web:6bf3f10293847561029384',
    messagingSenderId: '1049749225213',
    projectId: 'library-managment-6bf3f',
    authDomain: 'library-managment-6bf3f.firebaseapp.com',
    storageBucket: 'library-managment-6bf3f.appspot.com',
  );
}
